#
#
# Copyright © 2021-2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "powerstore-nfs"
provisioner: "csi-powerstore.dellemc.com"
parameters:
  # arrayID: id of array to be used for volumes
  # Allowed values: arrayID corresponding to array's globalID specified in secret.yaml
  # Optional: false
  # Default value: None
  arrayID: "Unique"

  # FsType: file system type for mounted volumes
  # Allowed values:
  #   ext3: ext3 filesystem type
  #   ext4: ext4 filesystem type
  #   xfs: XFS filesystem type
  #   nfs: NFS filesystem
  # Optional: true
  # Default value: None if defaultFsType is not mentioned in values.yaml
  # Else defaultFsType value mentioned in values.yaml
  # will be used as default value
  csi.storage.k8s.io/fstype: "nfs"
  # nasName: NAS server's name. If not specified, value from secret.yaml will be used
  # User can specify one or multiple NAS servers, separated by commas.
  # Allowed values: string
  # Optional: true
  # Default value: None
  nasName: "nas-server1,nas-server2,nas-server3"

  # allowRoot: enables or disables root squashing (valid only for NFS)
  # Allowed values:
  #   true: will allow root users to use their privileges
  #   false: will prevent root users on NFS clients from exercising root privileges on the NFS server
  # Optional: true
  # Default value: false
  allowRoot: "false"

  # nfsAcls: enables setting permissions on NFS mount directory
  # This value overrides the NFS ACL (nfsAcls) attribute of corresponding array config in secret, if present
  # Permissions can be specified in two formats:
  #   1) Unix mode (NFSv3)
  #   2) NFSv4 ACLs (NFSv4)
  #      NFSv4 ACLs are supported on NFSv4 share only.
  # Allowed values:
  #   1) Unix mode: valid octal mode number
  #      Examples: "0777", "777", "0755"
  #   2) NFSv4 acls: valid NFSv4 acls, seperated by comma
  #      Examples: "A::OWNER@:RWX,A::GROUP@:RWX", "A::OWNER@:rxtncy"
  # Optional: true
  # Default value: "0777"
  # nfsAcls: "0777"

# reclaimPolicy: PVs that are dynamically created by a StorageClass will have the reclaim policy specified here
# Allowed values:
#   Reclaim: retain the PV after PVC deletion
#   Delete: delete the PV after PVC deletion
# Optional: true
# Default value: Delete
reclaimPolicy: Delete

# allowVolumeExpansion: allows the users to resize the volume by editing the corresponding PVC object
# Allowed values:
#   true: allow users to resize the PVC
#   false: does not allow users to resize the PVC
# Optional: true
# Default value: false
allowVolumeExpansion: true

# volumeBindingMode controls when volume binding and dynamic provisioning should occur.
# Allowed values:
#   Immediate: indicates that volume binding and dynamic provisioning occurs once the
#   PersistentVolumeClaim is created
#   WaitForFirstConsumer: will delay the binding and provisioning of a PersistentVolume
#   until a Pod using the PersistentVolumeClaim is created
# Optional: true
# Default value: Immediate
volumeBindingMode: Immediate
