name: Release CSI-Powerstore
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      option:
          description: 'Select version to release'
          required: true
          type: choice
          options:
            - major
            - minor
            - patch
jobs:
  csm-release:
    uses: harishp8889/test-common-github-actions/.github/workflows/csm-release-driver-module.yaml@main
    name: Release CSM Drivers and Modules
    with:
      version: ${{ github.event.inputs.version }}
      images: "csi-powerstore"
    secrets: inherit
